/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import civitas.CivitasJuego;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import javax.swing.JOptionPane;
import civitas.Diario;
import GUI.VistaDado;
import civitas.Jugador;
import java.util.ArrayList;


public class CivitasView extends javax.swing.JFrame implements Vista{
    
    private CivitasJuego juego;
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
    }
    public void actualiza(){
        jugadorPanel1.setJugador(juego.getJugadorActual());
        panelCasilla1.setCasilla(juego.getTablero().getCasilla(juego.getJugadorActual().getCasillaActual()));
        area_ranking.setVisible(false);
        ranking_label.setVisible(false);
        
        if(juego.finalDelJuego()){
            area_ranking.setVisible(true);
            ranking_label.setVisible(true);
            //Creamos cadena para el ranking
            String mensaje = "";
            boolean tabulador=false; //Se crea para controlar saltos de linea del ranking
            ArrayList<Jugador>jugadores = juego.ranking();
            
            for(int i=0;i<jugadores.size();i++){
                if(!tabulador){
                    mensaje +=" Posicion " + (1+i) + jugadores.get(i).toString();
                    tabulador=true;
                }
                else
                    mensaje+="\n" + " Posicion " +(1+i) + jugadores.get(i).toString();  
            }
            
            area_ranking.setText(mensaje);
        }
        
        this.repaint();
        this.revalidate();
            
    }

    public void pausa(){
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?",
                    "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val==1) System.exit(0);
    }

    public Respuesta comprar(){
        int opcion= 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la " +
 "calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
         if(opcion == 0)
             return Respuesta.NO;
         
         else
             return Respuesta.SI;
                     
    }

    public OperacionInmobiliaria elegirOperacion (){
        
        GestionarDialog gestion = new GestionarDialog(this);
        
        return OperacionInmobiliaria.values()[gestion.getGestion()];
    }

    public int elegirPropiedad(){
       PropiedadDialog dialog = new PropiedadDialog(this, juego.getJugadorActual());
        return dialog.getPropiedadElegida();
    }

    public void mostrarSiguienteOperacion(OperacionJuego operacion){
        
        text_sigOperacion.setText(operacion.toString());
        
        if(operacion==(OperacionJuego.AVANZAR))
            VistaDado.createInstance(this);
        
        this.repaint();
        
    }
    
 
    @Override
    public void mostrarEventos(){
        DiarioDialog diarioD=null;
        if (!Diario.getInstance().getEventos().isEmpty())
            diarioD= new DiarioDialog(this); //crea la ventana del diario
        
    }  
    
    public void setCivitasJuego(CivitasJuego juego){
        
        this.juego=juego;
        setVisible(true);
        panelTablero1.setTablero(juego);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ranking_area = new javax.swing.JTextArea();
        label_titulo = new javax.swing.JLabel();
        jugadorPanel1 = new GUI.JugadorPanel();
        ranking_label = new javax.swing.JLabel();
        label_sig_operacion = new javax.swing.JLabel();
        text_sigOperacion = new javax.swing.JTextField();
        label_info_casilla = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_ranking = new javax.swing.JTextArea();
        label_jugador = new javax.swing.JLabel();
        panelCasilla1 = new GUI.PanelCasilla();
        panelTablero1 = new GUI.PanelTablero();

        ranking_area.setColumns(20);
        ranking_area.setRows(5);
        jScrollPane1.setViewportView(ranking_area);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        label_titulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 0, 0));
        label_titulo.setText("CIVITAS");

        ranking_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ranking_label.setForeground(new java.awt.Color(0, 0, 0));
        ranking_label.setText("Ranking");

        label_sig_operacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_sig_operacion.setForeground(new java.awt.Color(0, 0, 0));
        label_sig_operacion.setText("Siguiente Operacion");

        text_sigOperacion.setBackground(new java.awt.Color(255, 255, 204));
        text_sigOperacion.setText("                ");
        text_sigOperacion.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        text_sigOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_sigOperacionActionPerformed(evt);
            }
        });

        label_info_casilla.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        label_info_casilla.setForeground(new java.awt.Color(0, 0, 0));
        label_info_casilla.setText("INFORMACION CASILLA");

        area_ranking.setBackground(new java.awt.Color(255, 255, 204));
        area_ranking.setColumns(20);
        area_ranking.setRows(5);
        jScrollPane2.setViewportView(area_ranking);

        label_jugador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_jugador.setForeground(new java.awt.Color(0, 0, 0));
        label_jugador.setText("JUGADOR");

        panelCasilla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelTablero1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_sig_operacion)
                            .addComponent(text_sigOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 349, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ranking_label)
                        .addGap(123, 123, 123))))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(label_jugador)
                .addGap(239, 239, 239)
                .addComponent(label_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(panelTablero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelCasilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_info_casilla))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label_sig_operacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_sigOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ranking_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_info_casilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCasilla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTablero1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label_jugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_sigOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_sigOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_sigOperacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_ranking;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private GUI.JugadorPanel jugadorPanel1;
    private javax.swing.JLabel label_info_casilla;
    private javax.swing.JLabel label_jugador;
    private javax.swing.JLabel label_sig_operacion;
    private javax.swing.JLabel label_titulo;
    private GUI.PanelCasilla panelCasilla1;
    private GUI.PanelTablero panelTablero1;
    private javax.swing.JTextArea ranking_area;
    private javax.swing.JLabel ranking_label;
    private javax.swing.JTextField text_sigOperacion;
    // End of variables declaration//GEN-END:variables
}
