/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.Jugador;
import java.util.ArrayList;
import civitas.CasillaCalle;

public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */
    
    private Jugador jugador;
    
    public JugadorPanel() {
        initComponents();
    }
    
    public void setJugador(Jugador jugador){
        this.jugador = jugador;
    
        nombre.setText(jugador.getNombre());
        
        saldo.setText(Float.toString(jugador.getSaldo()));
        
        especulador.setText(Boolean.toString(jugador.EsEspeculador()));
        
        this.rellenaPropiedades(jugador.getPropiedades());
        
        this.repaint();
        revalidate();
    }
    private void rellenaPropiedades (ArrayList<CasillaCalle> lista) {
        // Se elimina la información antigua
        propiedadesPanel.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas
        //individuales y añadirlas al panel
        
        for (CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);

            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
       }
        // Se fuerza la actualización visual del panel propiedades y del
        // panel del jugador
        repaint();
        revalidate();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        label_saldo = new javax.swing.JLabel();
        label_especulador = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        especulador = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        label_nombre.setText("Nombre");
        add(label_nombre);

        label_saldo.setText("Saldo");
        add(label_saldo);

        label_especulador.setText("Especulador");
        add(label_especulador);

        nombre.setEditable(false);
        nombre.setText("nombre");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        add(nombre);

        saldo.setEditable(false);
        saldo.setText("saldo");
        add(saldo);

        especulador.setEditable(false);
        especulador.setText("especulador");
        add(especulador);
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField especulador;
    private javax.swing.JLabel label_especulador;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_saldo;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
