/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.CivitasJuego;

public class PanelTablero extends javax.swing.JPanel {
    
    private CivitasJuego civitas;
    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
    }

    public void setTablero(CivitasJuego juego){
        civitas=juego;
        
        casilla_1.setText((juego.getTablero().getCasilla(0).getNombre()));
        casilla_2.setText((juego.getTablero().getCasilla(1).getNombre()));
        casilla_3.setText((juego.getTablero().getCasilla(2).getNombre()));
        casilla_4.setText((juego.getTablero().getCasilla(3).getNombre()));
        casilla_5.setText((juego.getTablero().getCasilla(4).getNombre()));
        casilla_6.setText((juego.getTablero().getCasilla(5).getNombre()));
        casilla_7.setText((juego.getTablero().getCasilla(6).getNombre()));
        casilla_8.setText((juego.getTablero().getCasilla(7).getNombre()));
        casilla_9.setText((juego.getTablero().getCasilla(8).getNombre()));
        casilla_10.setText((juego.getTablero().getCasilla(9).getNombre()));
        casilla_11.setText((juego.getTablero().getCasilla(10).getNombre()));
        casilla_12.setText((juego.getTablero().getCasilla(11).getNombre()));
        casilla_13.setText((juego.getTablero().getCasilla(12).getNombre()));
        casilla_14.setText((juego.getTablero().getCasilla(13).getNombre()));
        casilla_15.setText((juego.getTablero().getCasilla(14).getNombre()));
        casilla_16.setText((juego.getTablero().getCasilla(15).getNombre()));
        casilla_17.setText((juego.getTablero().getCasilla(16).getNombre()));
        casilla_18.setText((juego.getTablero().getCasilla(17).getNombre()));
        casilla_19.setText((juego.getTablero().getCasilla(18).getNombre()));
        casilla_20.setText((juego.getTablero().getCasilla(19).getNombre()));
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casilla_20 = new javax.swing.JTextField();
        casilla_19 = new javax.swing.JTextField();
        casilla_18 = new javax.swing.JTextField();
        casilla_1 = new javax.swing.JTextField();
        casilla_17 = new javax.swing.JTextField();
        casilla_15 = new javax.swing.JTextField();
        casilla_16 = new javax.swing.JTextField();
        casilla_13 = new javax.swing.JTextField();
        casilla_6 = new javax.swing.JTextField();
        casilla_4 = new javax.swing.JTextField();
        casilla_3 = new javax.swing.JTextField();
        casilla_5 = new javax.swing.JTextField();
        casilla_7 = new javax.swing.JTextField();
        casilla_8 = new javax.swing.JTextField();
        casilla_9 = new javax.swing.JTextField();
        casilla_2 = new javax.swing.JTextField();
        casilla_14 = new javax.swing.JTextField();
        casilla_11 = new javax.swing.JTextField();
        casilla_10 = new javax.swing.JTextField();
        casilla_12 = new javax.swing.JTextField();

        casilla_20.setEditable(false);
        casilla_20.setBackground(new java.awt.Color(255, 204, 255));
        casilla_20.setForeground(new java.awt.Color(0, 0, 0));
        casilla_20.setText("20");
        casilla_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_20ActionPerformed(evt);
            }
        });

        casilla_19.setEditable(false);
        casilla_19.setBackground(new java.awt.Color(255, 204, 204));
        casilla_19.setForeground(new java.awt.Color(0, 0, 0));
        casilla_19.setText("19");
        casilla_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_19ActionPerformed(evt);
            }
        });

        casilla_18.setEditable(false);
        casilla_18.setBackground(new java.awt.Color(204, 255, 255));
        casilla_18.setForeground(new java.awt.Color(0, 0, 0));
        casilla_18.setText("18");

        casilla_1.setEditable(false);
        casilla_1.setBackground(new java.awt.Color(255, 0, 0));
        casilla_1.setForeground(new java.awt.Color(0, 0, 0));
        casilla_1.setText("1");
        casilla_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_1ActionPerformed(evt);
            }
        });

        casilla_17.setEditable(false);
        casilla_17.setBackground(new java.awt.Color(51, 153, 255));
        casilla_17.setForeground(new java.awt.Color(0, 0, 0));
        casilla_17.setText("17");

        casilla_15.setEditable(false);
        casilla_15.setBackground(new java.awt.Color(255, 204, 102));
        casilla_15.setForeground(new java.awt.Color(0, 0, 0));
        casilla_15.setText("15");
        casilla_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_15ActionPerformed(evt);
            }
        });

        casilla_16.setEditable(false);
        casilla_16.setBackground(new java.awt.Color(255, 204, 255));
        casilla_16.setForeground(new java.awt.Color(0, 0, 0));
        casilla_16.setText("16");
        casilla_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_16ActionPerformed(evt);
            }
        });

        casilla_13.setEditable(false);
        casilla_13.setBackground(new java.awt.Color(153, 255, 153));
        casilla_13.setForeground(new java.awt.Color(0, 0, 0));
        casilla_13.setText("13");
        casilla_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_13ActionPerformed(evt);
            }
        });

        casilla_6.setEditable(false);
        casilla_6.setBackground(new java.awt.Color(204, 153, 255));
        casilla_6.setForeground(new java.awt.Color(0, 0, 0));
        casilla_6.setText("6");
        casilla_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_6ActionPerformed(evt);
            }
        });

        casilla_4.setEditable(false);
        casilla_4.setBackground(new java.awt.Color(153, 255, 204));
        casilla_4.setForeground(new java.awt.Color(0, 0, 0));
        casilla_4.setText("4");
        casilla_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_4ActionPerformed(evt);
            }
        });

        casilla_3.setEditable(false);
        casilla_3.setBackground(new java.awt.Color(204, 255, 153));
        casilla_3.setForeground(new java.awt.Color(0, 0, 0));
        casilla_3.setText("3");

        casilla_5.setEditable(false);
        casilla_5.setBackground(new java.awt.Color(0, 153, 204));
        casilla_5.setForeground(new java.awt.Color(0, 0, 0));
        casilla_5.setText("5");

        casilla_7.setEditable(false);
        casilla_7.setBackground(new java.awt.Color(255, 204, 204));
        casilla_7.setForeground(new java.awt.Color(0, 0, 0));
        casilla_7.setText("7");
        casilla_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_7ActionPerformed(evt);
            }
        });

        casilla_8.setEditable(false);
        casilla_8.setBackground(new java.awt.Color(204, 255, 255));
        casilla_8.setForeground(new java.awt.Color(0, 0, 0));
        casilla_8.setText("8");

        casilla_9.setEditable(false);
        casilla_9.setBackground(new java.awt.Color(204, 255, 204));
        casilla_9.setForeground(new java.awt.Color(0, 0, 0));
        casilla_9.setText("9");
        casilla_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_9ActionPerformed(evt);
            }
        });

        casilla_2.setEditable(false);
        casilla_2.setBackground(new java.awt.Color(255, 255, 153));
        casilla_2.setForeground(new java.awt.Color(0, 0, 0));
        casilla_2.setText("2");

        casilla_14.setEditable(false);
        casilla_14.setBackground(new java.awt.Color(255, 255, 153));
        casilla_14.setForeground(new java.awt.Color(0, 0, 0));
        casilla_14.setText("14");

        casilla_11.setEditable(false);
        casilla_11.setBackground(new java.awt.Color(102, 153, 255));
        casilla_11.setForeground(new java.awt.Color(0, 0, 0));
        casilla_11.setText("11");

        casilla_10.setEditable(false);
        casilla_10.setBackground(new java.awt.Color(255, 153, 255));
        casilla_10.setForeground(new java.awt.Color(0, 0, 0));
        casilla_10.setText("10");
        casilla_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_10ActionPerformed(evt);
            }
        });

        casilla_12.setEditable(false);
        casilla_12.setBackground(new java.awt.Color(204, 204, 255));
        casilla_12.setForeground(new java.awt.Color(0, 0, 0));
        casilla_12.setText("12");
        casilla_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(casilla_20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casilla_1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casilla_19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(casilla_18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(casilla_16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casilla_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(casilla_3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(casilla_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(casilla_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casilla_15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(casilla_14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(casilla_13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(casilla_12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casilla_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casilla_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(casilla_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla_19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casilla_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla_11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void casilla_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_1ActionPerformed

    private void casilla_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_15ActionPerformed

    private void casilla_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_13ActionPerformed

    private void casilla_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_10ActionPerformed

    private void casilla_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_7ActionPerformed

    private void casilla_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_6ActionPerformed

    private void casilla_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_4ActionPerformed

    private void casilla_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_9ActionPerformed

    private void casilla_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_12ActionPerformed

    private void casilla_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_16ActionPerformed

    private void casilla_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_19ActionPerformed

    private void casilla_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField casilla_1;
    private javax.swing.JTextField casilla_10;
    private javax.swing.JTextField casilla_11;
    private javax.swing.JTextField casilla_12;
    private javax.swing.JTextField casilla_13;
    private javax.swing.JTextField casilla_14;
    private javax.swing.JTextField casilla_15;
    private javax.swing.JTextField casilla_16;
    private javax.swing.JTextField casilla_17;
    private javax.swing.JTextField casilla_18;
    private javax.swing.JTextField casilla_19;
    private javax.swing.JTextField casilla_2;
    private javax.swing.JTextField casilla_20;
    private javax.swing.JTextField casilla_3;
    private javax.swing.JTextField casilla_4;
    private javax.swing.JTextField casilla_5;
    private javax.swing.JTextField casilla_6;
    private javax.swing.JTextField casilla_7;
    private javax.swing.JTextField casilla_8;
    private javax.swing.JTextField casilla_9;
    // End of variables declaration//GEN-END:variables
}
