/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;

public class PanelCasilla extends javax.swing.JPanel {

    /**
     * Creates new form PanelCasilla
     */
    private Casilla casilla;
    
    public PanelCasilla() {
        initComponents();
    }

    public void setCasilla(Casilla casilla){
        
        this.casilla=casilla;
        valor_nombre.setText(casilla.getNombre());
        valor_tipo.setText("Descanso");
        valor_propietario.setVisible(false);
        Precios.setVisible(false);
        Compra.setVisible(false);   
        Alquiler.setVisible(false);
        Edificar.setVisible(false);
        Propietario.setVisible(false);
        label_compra.setVisible(false);
        label_alquiler.setVisible(false);
        label_edificar.setVisible(false);
            
        if(casilla.esCalle()){
            
            valor_propietario.setVisible(true);
            Precios.setVisible(true);
            Compra.setVisible(true);
            Alquiler.setVisible(true);
            Edificar.setVisible(true);
            Propietario.setVisible(true);
            label_compra.setVisible(true);
            label_alquiler.setVisible(true);
            label_edificar.setVisible(true);

            valor_tipo.setText("Calle");
            valor_propietario.setText(((CasillaCalle)casilla).getPropietario());

            Compra.setText(Float.toString(((CasillaCalle)casilla).getPrecioCompra()));
            Alquiler.setText(Float.toString(((CasillaCalle)casilla).getPrecioAlquilerCompleto()));
            Edificar.setText(Float.toString(((CasillaCalle)casilla).getPrecioEdificar()));
        }
        
        else if(casilla.esSorpresa()){
            valor_tipo.setText("Sorpresa"); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Compra = new javax.swing.JTextField();
        Edificar = new javax.swing.JTextField();
        Alquiler = new javax.swing.JTextField();
        Precios = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Propietario = new javax.swing.JLabel();
        valor_propietario = new javax.swing.JTextField();
        valor_nombre = new javax.swing.JTextField();
        valor_tipo = new javax.swing.JTextField();
        label_compra = new javax.swing.JLabel();
        label_alquiler = new javax.swing.JLabel();
        label_edificar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        Compra.setBackground(new java.awt.Color(255, 255, 255));
        Compra.setForeground(new java.awt.Color(0, 0, 0));
        Compra.setText("compra");

        Edificar.setBackground(new java.awt.Color(255, 255, 255));
        Edificar.setForeground(new java.awt.Color(0, 0, 0));
        Edificar.setText("edificar");
        Edificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdificarActionPerformed(evt);
            }
        });

        Alquiler.setBackground(new java.awt.Color(255, 255, 255));
        Alquiler.setForeground(new java.awt.Color(0, 0, 0));
        Alquiler.setText("alquiler");

        Precios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Precios.setForeground(new java.awt.Color(0, 0, 0));
        Precios.setText("Precios");

        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre");

        Tipo.setForeground(new java.awt.Color(0, 0, 0));
        Tipo.setText("Tipo");

        Propietario.setForeground(new java.awt.Color(0, 0, 0));
        Propietario.setText("Propietario");

        valor_propietario.setBackground(new java.awt.Color(255, 255, 255));
        valor_propietario.setForeground(new java.awt.Color(0, 0, 0));
        valor_propietario.setText("propietario");

        valor_nombre.setBackground(new java.awt.Color(255, 255, 255));
        valor_nombre.setForeground(new java.awt.Color(0, 0, 0));
        valor_nombre.setText("nombre");

        valor_tipo.setBackground(new java.awt.Color(255, 255, 255));
        valor_tipo.setForeground(new java.awt.Color(0, 0, 0));
        valor_tipo.setText("tipo");

        label_compra.setForeground(new java.awt.Color(0, 0, 0));
        label_compra.setText("Compra");

        label_alquiler.setForeground(new java.awt.Color(0, 0, 0));
        label_alquiler.setText("Edificar");

        label_edificar.setForeground(new java.awt.Color(0, 0, 0));
        label_edificar.setText("Alquiler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Propietario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Precios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                    .addComponent(label_compra)
                    .addComponent(label_alquiler)
                    .addComponent(label_edificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(valor_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Propietario)
                    .addComponent(valor_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(Precios, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_compra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Edificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_alquiler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_edificar))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EdificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alquiler;
    private javax.swing.JTextField Compra;
    private javax.swing.JTextField Edificar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Precios;
    private javax.swing.JLabel Propietario;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel label_alquiler;
    private javax.swing.JLabel label_compra;
    private javax.swing.JLabel label_edificar;
    private javax.swing.JTextField valor_nombre;
    private javax.swing.JTextField valor_propietario;
    private javax.swing.JTextField valor_tipo;
    // End of variables declaration//GEN-END:variables
}
